### ISSUE TITLE
Erreur Fichier MetaUninst.cab not found lors de l'installation

### ISSUE THREAD

**Issue by reivaxy** [cperrot-inra/Graphe#1]
Impossible d'installer sur windows 10
Après clonage du repo, lancement de setup.exe, acceptation de la licence, message d'erreur MetaUninst.cab not found

**Comment by cperrot-inra** [comment]
Bonjour,
Désolé, il manquait effectivement des fichiers. Vous pouvez de nouveau cloner le repository.

**Comment by reivaxy** [comment]
Merci, ça marche maintenant !

**Comment by cperrot-inra** [comment]
Merci de me donner un retour sur votre usage de ce logiciel.

**Comment by cperrot-inra** [comment]
> 
> 
> Merci, ça marche maintenant !

Merci de me donner un retour sur votre usage de ce logiciel.
